# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MovieDatabase24i' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDatabase24i
  pod 'AFNetworking', '~> 4.0'
  pod 'XCDYouTubeKit', '~> 2.13'

  target 'MovieDatabase24iTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDatabase24iUITests' do
    # Pods for testing
  end

end
